-- Sales Analysis
-- What is the total revenue generated by each store location?
select
	store_location,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by store_location
order by total_revenue desc;

-- Which product category generates the highest revenue?
select
	product_category,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by product_category
order by total_revenue;

-- What are the top 10 best-selling products by quantity sold?
select
	top 10
	product_detail,
	sum(transaction_qty) as total_qty
from coffee_sales
group by product_detail
order by total_qty desc;

-- What is the average transaction value for each store?
select
	store_id,
	count(*) as total_orders,
	sum(transaction_qty*unit_price) as total_revenue,
	sum(transaction_qty*unit_price)/count(*) as avg_transaction_value
from coffee_sales
group by store_id
order by avg_transaction_value desc;

-- Which day has the highest total sales revenue?
select
	transaction_date,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by transaction_date
order by total_revenue desc;

-- Product Performance
-- Which product type sells the most units?
select
	product_type,
	sum(transaction_qty) as selling_units
from coffee_sales
group by product_type
order by selling_units desc;

-- What are the top 5 highest-revenue products?
select
	top 5
	product_type,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by product_type
order by total_revenue desc;

-- Which product category has the highest average unit price?
select
	product_category,
	cast(round(avg(unit_price),2) as decimal(10,2)) as avg_unit_price
from coffee_sales
group by product_category
order by avg_unit_price desc;

-- What percentage of total sales comes from each product category?
select
	product_category,
    cast(round(
    sum(transaction_qty*unit_price) * 100/
    (
    select sum(transaction_qty*unit_price)
    from coffee_sales
    ),
    2
    ) as decimal(10,2)) as sale_percentage
from coffee_sales
group by product_category
order by sale_percentage desc;

-- Which products are sold most frequently (highest number of transactions)?
select
	product_type,
	count(*) as total_orders
from coffee_sales
group by product_type
order by total_orders desc;

-- Time-Based Analysis
-- What are the busiest hours of the day based on transaction count?
select
	transaction_date,
	datepart(hour,transaction_time) as hour,
	count(*) as total_orders
from coffee_sales
group by transaction_date,datepart(hour,transaction_time)
order by total_orders desc;

select
	datepart(hour,transaction_time) as hour,
	count(*) as total_orders
from coffee_sales
group by datepart(hour,transaction_time)
order by total_orders desc;

-- At what time period is the highest revenue generated?
select
	datepart(hour,transaction_time) as hour,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by datepart(hour,transaction_time)
order by total_revenue desc;

-- How do morning, afternoon, and evening sales compare?
select
	case
	when datepart(hour,transaction_time) between 6 and 11 then 'Morning'
	when datepart(hour,transaction_time) between 12 and 17 then 'Afternoon'
	else 'Evening' end as time_period,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by case
	when datepart(hour,transaction_time) between 6 and 11 then 'Morning'
	when datepart(hour,transaction_time) between 12 and 17 then 'Afternoon'
	else 'Evening' end
order by total_revenue desc;

-- Store Performance
-- Which store location has the highest average order quantity per transaction?
select
	store_location,
	avg(transaction_qty) as avg_order_qty
from coffee_sales
group by store_location
order by avg_order_qty desc;   

-- Which store sells the most units of each product category?
select
	store_id,
	product_category,
	count(transaction_qty) as unit_sold
from coffee_sales
group by store_id,product_category
order by unit_sold desc;

select
	year(transaction_date) as year,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by year(transaction_date)
order by total_revenue desc;  

select
	month(transaction_date) as month,
	format(transaction_date,'MMM') as month_name,
	sum(transaction_qty*unit_price) as total_revenue
from coffee_sales
group by month(transaction_date),format(transaction_date,'MMM') 
order by month;       